# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /problem1

# Copy the current directory contents into the container at /problem1
COPY . .

# Run problem1.py when the container launches
CMD ["python", "./problem1.py"]